CREATE TABLE affected_versions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version_expression VARCHAR(255)                            NOT NULL,
    vulnerability_id   UUID                                    NOT NULL,
    CONSTRAINT pk_affected_versions PRIMARY KEY (id)
);

CREATE TABLE components
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_components PRIMARY KEY (id)
);

CREATE TABLE project_dependencies
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id              UUID                                    NOT NULL,
    dependendy_component_id BIGINT                                  NOT NULL,
    version                 VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_project_dependencies PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id          UUID                        NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    owner_id    UUID                        NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              UUID                        NOT NULL,
    user_name       VARCHAR(255)                NOT NULL,
    nick_name       VARCHAR(255)                NOT NULL,
    password_hash   VARCHAR(255)                NOT NULL,
    permission      VARCHAR(255)                NOT NULL,
    register_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_login_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vulnerabilities
(
    id                    UUID                        NOT NULL,
    cve_id                VARCHAR(255)                NOT NULL,
    title                 VARCHAR(255)                NOT NULL,
    description           VARCHAR(4000),
    severity              VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    affected_component_id BIGINT                      NOT NULL,
    CONSTRAINT pk_vulnerabilities PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (user_name);

ALTER TABLE vulnerabilities
    ADD CONSTRAINT uc_vulnerabilities_cveid UNIQUE (cve_id);

ALTER TABLE affected_versions
    ADD CONSTRAINT FK_AFFECTED_VERSIONS_ON_VULNERABILITY FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE project_dependencies
    ADD CONSTRAINT FK_PROJECT_DEPENDENCIES_ON_DEPENDENCY_COMPONENT FOREIGN KEY (dependency_component_id) REFERENCES components (id);

ALTER TABLE project_dependencies
    ADD CONSTRAINT FK_PROJECT_DEPENDENCIES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE vulnerabilities
    ADD CONSTRAINT FK_VULNERABILITIES_ON_AFFECTED_COMPONENT FOREIGN KEY (affected_component_id) REFERENCES components (id);